### ISSUE TITLE
GGST: Unknown2173 = start of recovery ?

### ISSUE THREAD

**Issue by wbrbr** [super-continent/bbscript#14]
Hi and thanks for the cool project. I've been looking at interpreting BBScript to automatically generate frame data, and this means finding when the startup/active/recovery frames begin.

I think the 2173 instruction has something to do with the start of recovery (kind of like the recoveryState instruction). Here are the clues:

Let's look at the 'cmn_AttackEnd' subroutine:
```
beginSubroutine: s32'cmn_AttackEnd'
  Unknown2173: 
  Unknown2033: 23, s32'NmlAtk5CFar'
  ifNot: (VARIABLE), 0
    Unknown2033: 23, s32'NmlAtk2C'
    ifNot: (VARIABLE), 0
      Unknown2033: 23, s32'NmlAtkAir5C'
      ifNot: (VARIABLE), 0
        Unknown2033: 23, s32'NmlAtk5D'
        ifNot: (VARIABLE), 0
          Unknown2033: 23, s32'NmlAtk2D'
          ifNot: (VARIABLE), 0
            Unknown2033: 23, s32'NmlAtk6D'
            ifNot: (VARIABLE), 0
              enableGatlings: 0
              enableWhiffCancel: 0
              Unknown1648: 0
              endIf: 
            endIf: 
          endIf: 
        endIf: 
      endIf: 
    endIf: 
  endSubroutine: 
```
 `Unknown2173` is the *only* instruction that is executed unconditionally, which means that it's probably the one that is responsible for actually ending the attack. And it is also the only one that doesn't take any argument.

This instruction is also used once in May's bbscript file, in the code for c.S:

```
beginState: s32'NmlAtk5CNear'
  upon: (IMMEDIATE)
    // skipped
    endUpon: 
  sprite: s32'may202_00', 2 // 2
  Unknown446: s32'202eff', 100
  sprite: s32'may202_01', 2 // 4
  sprite: s32'may202_02', 1 // 5
  Unknown621: 1, -1
  Unknown612: s32'SE_BTL_CMN_Swing_Hammer_Heavy_S'
  sprite: s32'may202_03', 1 // 6 + 1 = 7 startup frames
  sprite: s32'may202_04', 3 // 3
  hit: 
  callSubroutineWithArgs: s32'cmn_screenshake', (STATIC), 1, (STATIC), 0, (STATIC), 0, (STATIC), 0
  sprite: s32'may202_05', 3 // 6 active frames
  sprite: s32'may202_06', 4 // 4
  Unknown2173:                // <---- start of recovery
  Unknown1658: s32'Cancel_FDash'
  extendPushboxX: 0
  sprite: s32'may202_07', 2 // 6
  sprite: s32'may202_08', 2 // 8 recovery frames
  sprite: s32'may202_09', 2 // the frames after cmnNandemoCancel don't count
  callSubroutine: s32'cmnNandemoCancel'
  sprite: s32'may202_10', 2
  endState: 
```

If we take `Unknown2173` as the start of recovery we get exactly the same frame data as dustloop !

This instruction is also used once in Ky's script and same here it perfectly fits the frame data (also for c.S):

```
beginState: s32'NmlAtk5CNear'
  upon: (IMMEDIATE)
    // skipped
    endUpon: 
  sprite: s32'kyk202_00', 1
  sprite: s32'kyk202_01', 2
  sprite: s32'kyk202_02', 3 // 6 + 1 = 7 startup frames
  Unknown621: 1, -1
  Unknown612: s32'SE_BTL_CMN_Swing_Slash_Heavy_S'
  Unknown2526: 1, 1, 6, 100, 60, 200
  Unknown2591: 1, 1, 6, 100, 200, 200
  Unknown2581: s32'Weapon', s32'G_wep_grip', s32'Body', s32'G_grip_R'
  Unknown2524: s32'ex1', 0, 180000, -90000, 0, 0, 0, 0
  sprite: s32'kyk202_03', 2
  Unknown446: s32'kyk202_bake1', 100
  hit: 
  Unknown75: s32'cmn_screenshake', 0, 1, 0, 0, 0, 0, 0, 0
  Unknown2526: 1, 2, 6, 700, 60, 1000
  Unknown2591: 1, 2, 6, 700, 200, 1000
  Unknown2582: 
  Unknown2524: s32'ex1', 0, 0, 0, 0, 0, 0, 0
  sprite: s32'kyk202_04', 4 // 6 active frames
  Unknown32: s32'kyk202_bake1'
  Unknown446: s32'kyk202_bake2', 100
  sprite: s32'kyk202_05', 6
  Unknown2173: 
  extendPushboxX: 0
  sprite: s32'kyk202_06', 7 // 13 recovery frames
  sprite: s32'kyk202_07', 6
  callSubroutine: s32'cmnNandemoCancel'
  sprite: s32'kyk202_08', 6
  sprite: s32'kyk202_09', 4
  sprite: s32'kyk202_10', 4
  sprite: s32'kyk202_11', 4
  endState: 
```

I think this is pretty good evidence. I just don't know what the difference would be between this instruction and `recoveryState` which also seems to signal the start of recovery.
